# -*- coding: utf-8 -*-
"""Python Module 1: Case Study - 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wRCND7Jzeh9u4cYNC7zEVbi5e45tX2wy

Problem Statement:
Consider yourself to be Sam who is a data scientist. He has been invited as a
guest lecturer at a college to take an introductory session on Python.
Tasks To Be Performed:
1. Create a list containing squares of numbers from 1 to 10 (HINT: use List
Comprehension).
"""

#Mthood1
squares_list_Mthood1=[1,4,9,16,25,36,49,64,81,100]
print(squares_list_Mthood1)

#Mthood1 - in this we don't need to squre first and loop and multiplilcation will take for us
squares_list_Mthood2 = [i**2 for i in range(1, 11)]
print(squares_list_Mthood2)

"""2. Write a function to check if the year number is a leap year.

"""

year = 2003
answer =""
if year % 400 == 0:
  answer="Yes"
elif year % 100 == 0:
  answer="No"
elif year % 4 == 0:
  answer="Yes"
else:
  answer="No"
if answer=="Yes":
  print("{0} is a leap year",year)
else:
  print("{0} is not a leap year",year)

"""3. Write a function to take an array and return another array that contains the
members of the first array that are even.



"""

import array
array1=array.array('i',[2,3,4,5,6,7,8,9,10])
array2=array.array('i', [0] * 10)
print(array1[0])
j=0
for i in range(0, 9):
  if array1[i]%2==0:
    array2[j]=array1[i]
    j=j+1
print(array2)

"""4. Write a function that takes 2 arrays and prints the members of the first
array that are present in the second array. (HINT: use Membership
Comprehension)
"""

def find_common_elements(array1, array2):
  common_elements = [element for element in array1 if element in array2]
  return common_elements

# Example usage
array1 = array.array('i', [1, 2, 3, 4, 5])
array2 = array.array('i', [2, 4, 6, 8])

common_elements = find_common_elements(array1, array2)

print("Common elements:", common_elements)

